config/routes.rb
Rails.application.routes.draw do
  resources :text_messages, except: [:edit, :update, :destroy] do
    collection do
        post 'reply'
    end
end
  resources :train_statuses, except: [:new, :edit, :update, :destroy]
  root "train_statuses#create"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
    before_save :default_values
    def default_values
      self.subscribed = true if self.subscribed.nil?
    end
end

app/models/text_message.rb
class TextMessage < ApplicationRecord
   validates :to, :body, presence: true
#    TODO: validate phone number for phone numberyness
end

app/models/train_status.rb
class TrainStatus < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        render 'train_statuses/new'
    end
end

app/controllers/text_messages_controller.rb
class TextMessagesController < ApplicationController
    skip_before_action :verify_authenticity_token

  def index
    @text_messages = TextMessage.all
  end

  def show
     @text_message = TextMessage.find(params[:id])
  end

  def new
    @text_message = TextMessage.new
  end

  def create
    @text_message = TextMessage.new(text_message_params)

      if @text_message.save
        TwilioTextMessenger.new(@text_message.body,@text_message.to).send
        redirect_to @text_message, notice: 'Text message was successfully created.'
      else
        respond_to do |format|
            format.html { render :new }
            format.json { render json: @text_message.errors, status: :unprocessable_entity }
        end
      end
  end

  def reply
    @from = (params['From'])
    @status_message = helpers.parse_sms(params)
    @text_message = TextMessage.new({to:@from,body:@status_message})

    if @text_message.save
        response = Twilio::TwiML::MessagingResponse.new do |r|
            r.message body: @status_message
        end
        render xml: response.to_s
      else
        respond_to do |format|
            format.html { render :new }
            format.json { render json: @text_message.errors, status: :unprocessable_entity }
        end
      end
  end

  private

  def text_message_params
    params.require(:text_message).permit(:to, :body)
  end
end

app/controllers/train_statuses_controller.rb
class TrainStatusesController < ApplicationController
    after_action :notify_subscribers, only: [:create]

  def index
    @train_statuses = TrainStatus.all
  end

  def show
    @train_status = TrainStatus.find(params[:id])
  end

  def create
    @status = MtaInfo.new.l_status
    @train_status = TrainStatus.new(message:@status)

    respond_to do |format|
      if @train_status.save
        format.html { redirect_to @train_status }
        format.json { render :show, status: :created, location: @train_status }
      else
        format.html { render :new }
        format.json { render json: @train_status.errors, status: :unprocessable_entity }
      end
    end
  end

  def notify_subscribers
    if TrainStatus.second_to_last.message == 'GOOD SERVICE' && TrainStatus.last.message != 'GOOD SERVICE'
        Subscriber.find_each do |subscriber|
            TwilioTextMessenger.new(TrainStatus.last.nessage,subscriber.phone_number).send
        end
    end
end


  def train_status_params
    params.require(:train_status).permit(:message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/text_messages_helper.rb
module TextMessagesHelper
   def parse_sms(sms)
    body = sms[:Body]&.strip&.upcase
    from = sms[:From]

    case body

    when 'START'
        subscriber = Subscriber.create(phone_number: from)
        return "The number #{from} has been subscribed to L train service fails!"

    when 'STOP'
        subscriber = Subscriber.find_by(phone_number: from)
        if subscriber
            subscriber.destroy
            return "The number #{from} has been unsubscribed."
        else
            return "You are already unsubscribed"
        end

    when 'STATUS'
        return "L train status: #{TrainStatus.last.message}"

    else
        return "Welcome to the L train hotline! Send START or STOP to manage your subscription, or just send STATUS to see how the L is doing!"
    end
end

end

app/helpers/train_statuses_helper.rb
module TrainStatusesHelper
end

app/views/home/index.html.erb
<h1>HOW IS THAT L TRAIN?</h1>
<%= render "train_statuses/new" %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/text_messages/_form.html.erb
<%= form_with(model: text_message, local: true) do |form| %>
  <% if text_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(text_message.errors.count, "error") %> prohibited this text_message from being saved:</h2>

      <ul>
      <% text_message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :to %>
    <%= form.text_field :to %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/text_messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Text Messages</h1>

<table>
  <thead>
    <tr>
      <th>To</th>
      <th>Body</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <>>
    <% @text_messages.each do |text_message| %>
      <tr>
        <td><%= text_message.to %></td>
        <td><%= text_message.body %></td>
        <td><%= text_message.created_at %></td>
        <td><%= link_to 'Show', text_message %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Text Message', new_text_message_path %>

app/views/text_messages/new.html.erb
<h1>New Text Message</h1>

<%= render 'form', text_message: @text_message %>

<%= link_to 'Back', text_messages_path %>

app/views/text_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>To:</strong>
  <%= @text_message.to %>
</p>

<p>
  <strong>Body:</strong>
  <%= @text_message.body %>
</p>

<%= link_to 'Back', text_messages_path %>

app/views/train_statuses/_form.html.erb
<%= form_with(model: train_status, local: true) do |form| %>
  <% if train_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(train_status.errors.count, "error") %> prohibited this train_status from being saved:</h2>

      <ul>
      <% train_status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/train_statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>L Train Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @train_statuses.each do |train_status| %>
      <tr>
        <td><%= train_status.message %></td>
        <td><%= train_status.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= button_to "Get the latest status!", action: 'create'%>

app/views/train_statuses/show.html.erb
<h2>Is the L working?</h2>
<p id="notice"><%= notice %></p>
<h1> <%= @train_status.message %>
</h1>
<h3>You can get the L status at any time by texting 706.701.2709!</h3>
<br>
<h4>Send status in an SMS!</h4>
<%= form_with(model: TextMessage.new, local: true) do |form| %>

  <div class="field">
    <%= form.label :to %>
    <%= form.text_field :to %>
  </div>

  <div class="actions">
    <%= form.hidden_field :body, value:@train_status.message %>
    <%= form.submit %>
  </div>
<% end %>

<%= button_to "Refresh L train status!", action: 'create'%>
<br>
<br>
<%= link_to 'See L-train status history', train_statuses_path %>